import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const navigationData = [
  {
    title: 'Home',
    href: '/'
  },
  {
    title: 'Blog',
    href: '/blog'
  },
  {
    title: 'About Us',
    href: '/about-us'
  },
  {
    title: 'Contacts',
    href: '/contact-us'
  }
]

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' data-scroll-behavior='smooth' className='h-full'>
      <body className={`${geistSans.variable} ${geistMono.variable} flex h-full flex-col antialiased`}>
        <Header navigationData={navigationData} />
        <div className='mx-auto w-full max-w-350 flex-1 border-x'>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
